[tool.ruff]
line-length = 99
exclude = [
    ".venv",
    "venv",
    ".git",
    "__pycache__",
    "mlruns",
    "build",
    "dist",
    "*.egg-info",
    "generate_test_benchmarks.py",
]

[tool.ruff.lint]
select = ["E", "F", "W", "C90", "I"] # Đã chuyển vào đây
ignore = ["E501"]                    # Đã chuyển vào đây

[tool.ruff.lint.per-file-ignores]
"notebooks/*" = ["F401", "F841"]
"tests/*" = ["F841"]